global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RouteX API Service
  - job_name: 'routex-api'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # RouteX Blockchain Service
  - job_name: 'routex-blockchain'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Ethereum Node Metrics (if available)
  - job_name: 'ethereum-node'
    static_configs:
      - targets: ['host.docker.internal:6060']
    metrics_path: '/debug/metrics/prometheus'
    scrape_interval: 30s

  # Custom RouteX Contract Metrics
  - job_name: 'routex-contracts'
    static_configs:
      - targets: ['host.docker.internal:9091']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # AI Service Metrics
  - job_name: 'routex-ai'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Cross-Chain Bridge Metrics
  - job_name: 'routex-bridge'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 60s