[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fuzz]
runs = 1000

[rpc_endpoints]
monad = "https://monad-rpc-endpoint"  # 替换为实际的 Monad RPC 端点

[etherscan]
monad = { key = "${MONAD_ETHERSCAN_API_KEY}" }